#指定运行环境
language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
script:
  - npm run build
#运行的脚本命令
after_script:
  - cd dist
  - git init
  - git config user.name "proto2014"
  - git config user.email "1124519515@qq.com"
  - git add ./dist
  - git commit -m "显示打包"
  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

env:
  global:
    - GH_REF: github.com/proto1994/react-infrastructure.git

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master