#指定运行环境
language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install
script:
  - npm run build
#运行的脚本命令
after_script:
  - git checkout gh-pages
  - git add .
  - git commit -m "显示打包"
  - git push origin gh-pages


#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master